### ISSUE TITLE
Deploying a new IOC version always fails to connect

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-cli#57]
So here is an interesting problem with use of K8S for IOCs.

When I do an upgrade to an IOC it always fails to connect (e.g. Aravis) and needs a restart to get a connection to the device.

This is because K8S starts the new pod while it is still terminating the old pod and therefore the old one holds the device connection for a while.

Todo:

- reduce the time taken for a pod to shutdown (currently its 10s of secs and this is an argument to the pod I believe)
- get ec deploy functions to remove scale the deployment and wait for termination before doing the new deployment.

@coretl @GDYendell something to be aware of.

**Comment by gilesknap** [comment]
Maybe we could do something wiith stop.sh which is already provided by ibek and registered with K8S but currently does nothing.

Attaching to console and sending ctrl D comes to mind.

**Comment by coretl** [comment]
@callumforrester is this a problem for blueapi?

**Comment by gilesknap** [comment]
It's worse that I thought. Alternate restarts of the IOC have the same symptom for the same reason.

**Comment by callumforrester** [comment]
We have had this problem with services that talk to a message queue, they may swallow commands meant for the new pods while terminating.

**Comment by keithralphs** [comment]
I've encountered similar but different behaviour when investigating remote debugging, in that a terminating pod can seem to hang around for quite a bit alongside its replacement, even if you put --grace-period=0 --force. In may case I was trying to port foward to an updated pod using kubectl, but doing so via the deployment so I didn't have to be specific about the pod name, on the assumption that k8s would select the new one as the old one was terminating, or just not there any more. What actually happened  was that it selected the first matching pod in the list of ones that it knew aboud, which often still include the 'deleted' (i.e. terminating one. Because the pos name is this case as the same apart from guid stil suffix, this mean that the first in the liust could still be the terminating one if  the guid of the new pod was alphabetically later than that of the second, resulting in the prot being forwarded to the dying pod.

**Comment by gilesknap** [comment]
This has been resolved via the use of statefulsets instead of deployments.

It simply requires replacing the word deployment with statefulset in your manifest. There is complete parity of function and syntax as far as I have discovered.

@keithralphs @callumforrester this maybe of interest?
