### ISSUE TITLE
ec ioc instances missing some tags?

### ISSUE THREAD

**Issue by marcelldls** [epics-containers/ec-cli#65]
Running command:
'ec --repo https://github.com/epics-containers/bl38p.git ioc instances bl38p-di-dcam-01'
Returns:
Nothing
Expected:
2023.11.1

**Comment by gilesknap** [comment]
hmm maybe this is #39 which I thought I hadd fixed.

**Comment by marcelldls** [comment]
If you try 'ec --repo "https://github.com/epics-containers/bl38p.git" ioc instances bl38p-ea-ioc-03' then I would also expect to see "2023.11.1". This case is not "new iocs that have never changed"  or "it gets an error if one of the tags is on the 1st commit"

**Comment by gilesknap** [comment]
My take is that that is expected. The idea of my tagging algorithm for IOC instances is that it only shows tags for which the IOC instance has changes since the last tag. That way an IOC that is really stable stays at an old version until it gets modifiied.

This image shows that there were no changes to the folder bl38p-ea-ioc-03 between tags `2023.10.61` and `2023.11.1`. So I think the output of your command above is correct.


![image](https://github.com/epics-containers/epics-containers-cli/assets/964827/34ad06c5-ab77-4564-8b94-bc2edece5d13)

**Comment by marcelldls** [comment]
Oops I thought I was looking at the changelog of `2023.11.1` at the time but it was actually the commits ahead - therefore i thought the changes were included but they are not released yet
